services:
  - type: web
    name: vacaturekanon-webhook
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python webhooks/handler.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
