services:
  - type: web
    name: recruitin-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 webhooks/handler.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
