plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/wouterarts/Library/CloudStorage/OneDrive-Gedeeldebibliotheken-Recruitin/output/vacaturekanon/sales-website"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/wouterarts/Library/CloudStorage/OneDrive-Gedeeldebibliotheken-Recruitin/output/vacaturekanon/sales-website"
command = "echo 'Deploying static site'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]